### ISSUE TITLE
Hide Sold Out Badge on Specific Product Category

### ISSUE THREAD

**Issue by katvondiesel** [CharlieEtienne/sold-out-badge-for-woocommerce#8]
We currently have the Sold Out Badge for WooCommerce plugin on our site but I need to be able to hide the "Sold Out" badge on products in a specific category. Is there a way to do that?

**Comment by CharlieEtienne** [comment]
Hi, if you are lucky enough to have cat name in product div css classes (as in many themes), you just need to do:

```css
.product_cat-YOUR_CATEGORY_SLUG .wcsob_soldout {
    display: none !important;
}
```

Don't forget to replace `YOUR_CATEGORY_SLUG` with your actual category slug.

If you don't have category slugs in div classes, you'll need to write some php in `functions.php` in your child theme...

Charlie
